sudo: required

language: generic

services:
  - docker

env:
  global:
    - qemu_version=4.2.0-2
    - target_version=6.3.4
    - target_platform=linux
  matrix:
    - target_arch=amd64 qemu_arch=x86_64 bin_arch="64 Bit" bin_platform=linux
    - target_arch=armv7 qemu_arch=arm bin_arch=ARMv7 bin_platform=arm
#    - target_arch=armv6 qemu_arch=arm bin_arch=ARMv6 bin_platform=arm
    - target_arch=arm64 qemu_arch=aarch64 bin_arch=ARM64 bin_platform=arm

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - mkdir $HOME/.docker
  - 'echo "{" > $HOME/.docker/config.json'
  - 'echo "  \"experimental\": \"enabled\"" >> $HOME/.docker/config.json'
  - 'echo "}" >> $HOME/.docker/config.json'
  - sudo service docker restart
  - mkdir bin

install:
  - docker run --rm --privileged multiarch/qemu-user-static:register
  - curl -sLO https://github.com/multiarch/qemu-user-static/releases/download/v${qemu_version}/qemu-${qemu_arch}-static.tar.gz;
  - tar -xzvf qemu-${qemu_arch}-static.tar.gz;
  - curl -sLO https://dl.grafana.com/oss/release/grafana-${target_version}.${target_platform}-${target_arch}.tar.gz
  - curl -sS https://grafana.com/grafana/download?platform=${bin_platform} | grep -oP "Standalone Linux Binaries.*${bin_arch}.*SHA256.*>\K.*" | sed "$ s/$/  grafana-${target_version}.${target_platform}-${target_arch}.tar.gz/" > sha256sums.txt
  - if [ ! -z "$(sha256sum -c sha256sums.txt 2> /dev/null | grep OK)" ]; then
      tar -xzvf grafana-${target_version}.${target_platform}-${target_arch}.tar.gz;
      cp grafana-${target_version}/bin/grafana-server ./bin/grafana-server_${target_arch};
      cp grafana-${target_version}/bin/grafana-cli ./bin/grafana-cli_${target_arch};
      cp -r grafana-${target_version}/public .;
      cp -r grafana-${target_version}/tools .;
      cp -r grafana-${target_version}/conf .;
      cp -r grafana-${target_version}/scripts .;
    fi;
  - rm -rf grafana-${target_version}
  - rm grafana-${target_version}.${target_platform}-${target_arch}.tar.gz
  - curl -sLO https://raw.githubusercontent.com/grafana/grafana/v${target_version}/packaging/docker/run.sh
  - chmod +x run.sh
  - docker build -f Dockerfile.${target_arch} -t ndanyluk/grafana-${target_arch}:$TRAVIS_BUILD_NUMBER .

script:
  - sudo docker run -d --name grafana ndanyluk/grafana-${target_arch}:$TRAVIS_BUILD_NUMBER
  - sleep 5
  - sudo docker ps | grep -q grafana

after_success:
  - if [ -z "$DOCKER_USER" ]; then
      echo "PR build, skipping Docker Hub push";
    elif [ "$TRAVIS_BRANCH" != "master" ]; then
      echo "Branch build, skipping Docker Hub push";
    else
      docker login -u "$DOCKER_USER" -p "$DOCKER_PASS";
      docker tag ndanyluk/grafana-${target_arch}:$TRAVIS_BUILD_NUMBER ndanyluk/grafana-${target_arch}:${target_version};
      docker tag ndanyluk/grafana-${target_arch}:$TRAVIS_BUILD_NUMBER ndanyluk/grafana-${target_arch}:latest;
      docker push ndanyluk/grafana-${target_arch}:${target_version};
      docker push ndanyluk/grafana-${target_arch}:latest;
    fi

jobs:
  include:
    - stage: deploy
      install: skip
      script: skip
      after_success:
        - if [ -z "$DOCKER_USER" ]; then
            echo "PR build, skipping Docker Hub push";
          elif [ "$TRAVIS_BRANCH" != "master" ]; then
            echo "Branch build, skipping Docker Hub push";
          else
            docker login -u "$DOCKER_USER" -p "$DOCKER_PASS";
            docker manifest create ndanyluk/grafana:${target_version} ndanyluk/grafana-armv7:${target_version} ndanyluk/grafana-arm64:${target_version} ndanyluk/grafana-amd64:${target_version};
            docker manifest create ndanyluk/grafana:latest ndanyluk/grafana-armv7:latest ndanyluk/grafana-amd64:latest ndanyluk/grafana-arm64:latest;
            docker manifest push ndanyluk/grafana:${target_version};
            docker manifest push ndanyluk/grafana:latest;
          fi
